global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'anton-orchestrator'
    static_configs:
      - targets: ['orchestrator:3002']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'anton-visual-editor'
    static_configs:
      - targets: ['visual-editor:3000']
    metrics_path: '/api/metrics'
    scrape_interval: 15s

  - job_name: 'anton-planning-service'
    static_configs:
      - targets: ['planning-service:3003']
    metrics_path: '/metrics'
    scrape_interval: 15s

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:80']
    metrics_path: '/nginx_status'
    scrape_interval: 30s